README.md
A site that shows some common sorting algorithms to give a nice overview as too how they work.
=> Visual presentations of sorting algorithms

README.md
Please take a look at [The Ten Rules of a Zen Programmer](https://www.zenprogrammer.org/en/the10rulesofazenprogrammer.html)
=> Added The Ten Rules of a Zen Programmer

README.md
There is a lot more to Secure Programming than OWASP; OWASP is actually just one area of a much wider field. David Wheeler's Secure Programming HOWTO goes into a lot more detail.
=> Enhancement: Secure Programming HOWTO

README.md
Included a link to a research paper that does a great job of explaining the various paradigms under the **Practices** section.
=> Programming Paradigms Paper

README.md
What Every Computer Scientist Should Know About Floating-Point Arithmetic
=> Added a link to What Every Computer Scientist Should Know About Floating-Point Arithmetic

README.md
Cracking the Coding Interview: Updating this very important book's link to the latest edition.
=> Cracking the Coding Interview book link updated to latest edition

README.md
Added a link to The mythical 10x programmer
Added a link to The Debugging Mindset
=> Added a link to The mythical 10x programmer and The Debugging Mindset

README.md
Add a Github Repo that have a tutorial of Regular Expression
=> Add Regex tutorial.

README.md
Really good introduction to bases (binary, decimal, etc), big/small endians, integer, long, floating points, and an overview of how computers count. Very easy to read!
=> Add book How to Count under Numbers section

README.md
This book expands on the career stuff from Soft Skills.
=> Added recently published companion to Soft Skills

README.md
Hey, Alexey, thank you for work! I read some of your posts, but remembered your "How to FP" guide which starts with POODR 😄. Totally second that 👍. 
I found learnxinyminutes really useful for me to get started quickly.
Hyperpolyglot is still useful, but maybe it's too specific.
I totally support that this list is **curated**, so feel free to decline or propose changes. 
As you can see, I added sentence which describes what it is about, but then found nothing had anything like that. And also, I didn't know at which category it belongs to, so I created **Languages** section.
=> Add Hyperpolyglot, learnxinyminutes

README.md
What Every Programmer Should Know About Memory is a modern classic. The paper explains in a really simple and interesting way how memory works and how a programmes should go about using memory.
=> Add What Every Programmer Should Know About Memory

CONTRIBUTING.md, README.md
Hey, thanks for good stuff. 
I just remembered about Exercism 😈 I decided to add it into doc.
Also added small style fix for *contributing* page.
=> New Coding practice site + small style fix

README.md
Hi!
[Project Euler](https://projecteuler.net/) is a coding practice website with lots of problems of varying difficulty that take a numerical answer instead of being evaluated by an online judge. This is very helpful for people who want to practice algorithms without the overhead required by typical coding practice sites. I thought it would be a great addition to the list
Thanks for your time!
=> add project euler to this list of programming sites

README.md
A pull request trying to add some resources about data structures implementation, as mentioned on #26 .
=> adding some data structures implementation resources

README.md
The website has great roadmap for practicing. It contains only real-world tasks asked in top tech companies. Tasks are marked by company names where they were asked.
The website has a positive reference from a Google employee: http://larrr.com/horoshij-resurs-dlya-podgotovki.
=> Add InterviewBit into Practice Section (corrected, on master branch)

README.md
Great site for coding practice. Many categories for practicing, like Algos, DB, Shell, etc. Many algo tasks have editorial clear and illustrated solutions. For sample: https://leetcode.com/articles/symmetric-tree.
=> Add LeetCode into Coding Practiсe section

CONTRIBUTING.md
=> Slight typo in CONTRIBUTING.md

README.md
This book is teaches the basics of organizing data and sets. Very useful book written by an MIT professor.
=> proof theory book for discrete math

README.md
Add :book: [Tech Interview Handbook](https://github.com/yangshun/tech-interview-handbook)
=> Add Tech Interview Handbook

README.md
lots of remote job information and resources
=> Add Awesome Remote Job

README.md
The book "Clean Code: A Handbook of Agile Software Craftsmanship", by Robert C. Martin is a must read for every software developer.
=> Added the book Clean Code

README.md
A useful post for someone learning to program
=> Add Teach Yourself Programming in Ten Years

README.md
* Add Don't Make Me Think by Steve Krug, a great book on software usability, especially on web/mobile.
=> Create UX/Usability section 

README.md
=> adding some problem solving resources

README.md
Amazing paper written by Dijkstra, in 1968, where he justifies why goto statements are harmful and should be avoided in the future.
=> Historical Paper by Dijkstra

README.md
This tutorial explains the ASCII & utf-8 way of representing characters in a computer.
It is very easy and clear explanation.
=> Add ASCII and UTF-8

README.md
Add future of programming by Bret Victor. This talk changes how you think about programming and even your life.
=> add future-of-programming video

README.md
This video inspired Lightable, Swift Playground, etc. It opened another gate to programming.
=> add inventing-on-principle video

README.md
Some great resources about dos and don'ts regarding cryptography for developers:
- :page_facing_up: [Cryptographic Right Answers](https://gist.github.com/tqbf/be58d2d39690c3b366ad)
- :page_facing_up: [An Open Letter to Developers Everywhere (About Cryptography)](https://gist.github.com/paragonie-scott/e9319254c8ecbad4f227)
=> Add some great recomendations about crypto

README.md
Hi! This is a guide for the developers who want to start their own business.
=> Add What you should know as a founder of a software company

CONTRIBUTING.md
* Change wording to close #93
* Remove trailing whitespace throughout
=> Update wording in CONTRIBUTING.md, closes #93

README.md
A really useful website to learn and practice coding.
=> Add Coding Practice Site CodeCombat

README.md
another coding interview online judgement service
=> add lintcode.com

README.md
Every javascript programmer must know and care about it, no matter low level or high level.
=> Add links "How javascript works"

README.md
repl.it is a great online editing environment for tons of languages.
=> Add `repl.it` to `Services`

README.md
Tested in Firefox 59.0.1 (x64) on Windows from Poland.
=> Switched to HTTPS links where it's possible

README.md
Added "The good software development manifesto" by Andrew C. Oliver.
=> Added Article Under Engineering Philosophy

README.md
Hello
I added a link at the end of Coding practice sites. Interview cake has amazing step by step break down on how to solve and approach problems. I thought this should be on this list.
=> Added Cake Interview link at the bottom of Coding Practice Sites

README.md
@mr-mig Please take a look at https://www.integralist.co.uk/posts/hashing-and-encryption/
=> Added Hashing, Encryption and Encoding

README.md
At Coder, have different contests, from multiple levels.
- Regular Contest
- Beginner Contest
- And sponsored contests as well.
Amazing editorial, weekly new problems. 
https://atcoder.jp/ranking
Is a great way to practice solving programming questions, and has a nice and gentle learning curve.
=> Add At Coder programming contest 

README.md
Added an article on How to Get a Tech Job Abroad Faster
=> Added an article on How to Get a Tech Job Abroad Faster

README.md
The website changed web-app and domain name, so I changed their names in `README.md`
=> Change CodeFights to CodeSignal

README.md
The website contains lecture videos and all materials covered in the course.
=> Update CS61B link to latest course website

README.md
I added two resources which will be useful for the programmer.
Security Resources
- [A collection of hacking/penetration testing resources to make you better!](https://github.com/vitalysim/Awesome-Hacking-Resources)
Licenses
- [How open source licenses work and how to add them to your projects](https://medium.freecodecamp.org/how-open-source-licenses-work-and-how-to-add-them-to-your-projects-34310c3cf94)
Both of them will help every programmer improve their skill better and kickstart their own opensource.
=> Add "How open source licenses work and how to add them to your projects" to list

README.md
Full disclaimer, I wrote [the content that I've linked to](https://www.deployhq.com/git).
That being said, I would not be making this pull request if I didn't believe that the content was genuinely of a good standard and helpful for beginners. See [this post on Reddit](https://www.reddit.com/r/learnprogramming/comments/bj1mcj/a_bunch_of_free_git_tutorials/) to see the feedback I've received.
If you'd prefer for me to add the link, rather than replace the existing one I'd be happy to do so.
=> Add a more comprehensive Git tutorial for beginners

README.md
https://github.com/mtdvio/every-programmer-should-know/issues/111
=> Added pramp.com in career section

README.md
Code Complete is a good book about best practices involved in Software Construction
=> Added the book 'Code Complete' under Practices category

README.md
Adds link to [Computer Science Roadmap](https://roadmap.sh/computer-science)
=> Add link to computer science roadmap

README.md
I would like to add the book "Introduction to Algorithms" by T. H. Cormen et al.
The only book listed here under the "Algorithms" category is currently Grokking Algorithms which is very beginner-friendly and has a lot of important algorithms and DS, but Introduction to Algorithms is another very well-known book on the topic which goes more in-depth than Grokking.
It expands on the topics in Grokking and also has important topics which aren't covered in Grokking such as Binary Search Trees, B-Trees, Red-Black Trees, Heaps, DFS, Kruskal, Floyd-Warshall, Ford-Fulkerson, Matrix operations and much more. 
For these reasons, I think it would be useful to include this book as a resource on algorithms that everyone should know.
=> Add "Introduction to Algorithms" book

README.md
For newbies, I think this could be the first step to start. It helps a lot to understand how algorithms works and their efficiency.
=> Add new book for starting with algoritms and distributed systems

README.md
add Algorithms for Competitive Programming, Arxiv, Sci-hub
=> add Algorithms, Paper

README.md
=> Updated SEO link

README.md
Codemia is a website for practicing system design problems like how you practice algorithms and data structures on Leetcode/CodeForce.
=> Update README.md to include Codemia in coding service section
